name: CI Test
on:
  push:
    branches: 
      - test/*

jobs:

  linux-windows-build:
    name: Linux & Windows Build
    runs-on: ubuntu-latest
    steps:

    - name: Go v1.14
        uses: actions/setup-go@v1
        with:
        go-version: 1.14
        id: go

    - name: Node v14
        uses: actions/setup-node@v1
        with:
            node-version: '14'
    - run: npm install -g ts-node typescript

    - name: OS Packages 
      run: |
      sudo apt-get update --fix-missing && sudo apt-get -y install \
      git build-essential zlib1g zlib1g-dev wget zip unzip \
      mingw-w64 binutils-mingw-w64 g++-mingw-w64
    
    - name: Protoc
      env:
        PROTOC_VER: 3.11.4
      run: |
        wget -O protoc-${PROTOC_VER}-linux-x86_64.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VER}/protoc-${PROTOC_VER}-linux-x86_64.zip \
        && unzip protoc-${PROTOC_VER}-linux-x86_64.zip \
        && sudo cp -vv ./bin/protoc /usr/local/bin/protoc
  
    - name: Protoc-gen-go
    env:
        PROTOC_GEN_GO_VER: 1.3.5
    run: |
        wget -O protoc-gen-go.tar.gz https://github.com/golang/protobuf/archive/v${PROTOC_GEN_GO_VER}.tar.gz \
        && tar xvf protoc-gen-go.tar.gz \
        && cd protobuf-${PROTOC_GEN_GO_VER} \
        && make install

    - name: Packr
    run: go get -u github.com/gobuffalo/packr/packr

    - name: Checkout Sliver
    uses: actions/checkout@v2
    with:
        repository: BishopFox/sliver

    - name: Go Assets
    run: |
      ls -lah && cd sliver \
      && ./go-assets.sh \
      && make static-linux \
      && cp sliver-server .. \

    - name: Make
    run: export PATH=/home/runner/go/bin/:$PATH && make static-linux
